schema_version = "1.0.0"

id = "sharp_polish"
version = "1.0.0"
name = "SharpPolish"
tagline = "Hard surface polishing with optional volume preservation"
maintainer = "YLIANG"
type = "add-on"

license = ["SPDX:GPL-3.0-or-later"]
blender_version_min = "4.2.0"
tags = ["Mesh"]
